GET http://localhost:3003/users
###

POST http://localhost:3003/users/signup
Content-Type: application/json

  {
    "name": "Anderson",
    "email": "anderson@email.com",
    "password": "23323212",
    "role": "user"
  }
###

POST http://localhost:3003/users/login
Content-Type: application/json

  {
    "name": "Anderson",
    "email": "anderson@email.com",
    "password": "23323212",
    "role": "user"
  }
###